title: Chenna Kautilya
url: "https://resume.chenna.me"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "hire@chenna.me"
   link: "mailto:hire@chenna.me"
